config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  # resources :questions, only: [:create]
  get 'export', to: 'questions#export'
  post 'import', to: 'questions#import'

  get 'mark_question_as_answered/:id', to: 'questions#mark_question_as_answered', as: 'mark_answered'
  get 'no_questions', to: 'questions#no_questions', as: 'no_questions'
  get 'toggle_language', to: 'questions#toggle_language', as: 'toggle_language'
  get 'get_question', to: 'questions#get_question', as: 'get_question'
  post 'send_message', to: 'questions#send_message', as: 'send_message'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  validate :qa_format

  def self.get_new_ids(question_type_, session_)
    always_answered = Answer.where(session_id: DateTime.parse(session_)).pluck(:question_id)
    where(lang: question_type_).ids.sample(4) - always_answered
  end

  def self.get_unanswered(question_type_, session_)
    where(id: get_new_ids(question_type_, session_))
  end

  def qa_format
    if question[0..2] != '<p>' || question[-4..-1] != '</p>' || answer[0..2] != '<p>' || answer[-4..-1] != '</p>'
      errors.add(:format, 'Wrong format: missing <p> tag')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include SetSession
  include SaveAllQuestions

  def index
    set_session
    @session_started = session[:last_time]

    @questions = Question.get_unanswered(session[:lang], session[:last_time]).map { |u| { category: u.category, id: u.id } }
    if @questions.length == 0
      redirect_to no_questions_path
    end
  end

  def no_questions; end

  def import
    @result = parse_and_save(params['file'])

    respond_to do |format|
      format.js { render 'import', status: @result }
    end
  end

  def export
    save_all_questions
    respond_to do |format|
      format.js
    end
  end

  def get_question
    @question = Question.find_by(id: params[:id])
    if request.xhr?
      render json: { question_content: @question.question, answer_content: @question.answer}
    end
  end

  def mark_question_as_answered
    Answer.create(question_id: params[:id], session_id: session[:last_time])
    respond_to do |format|
      format.js { head :ok }
    end
  end

  def toggle_language
    session[:lang] == 'JQuery' ? session[:lang] = 'RoR' : session[:lang] = 'JQuery'

    respond_to do |format|
      format.js
    end
  end

  def send_message
    doc = GeneratePdf.new
    doc.create_content(session[:last_time])
    doc.render_file 'qa.pdf'
    ApplicationMailer.send_message(params[:address]).deliver

    respond_to do |format|
      format.js { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_it
    session[:lang] == 'JQuery' ? true : false
  end
end

app/views/layouts/_left_bar.slim
.ui.visible.very.wide.sidebar.vertical.menu
  = link_to toggle_language_path, remote: true, class: 'item' do
    |  Change QA
    i.home.icon
  a.item
    = react_component 'Comp'
  a.item
    = react_component('Clock', session_: @session_started)
  a.item
    = react_component('ImportButton')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <div class="ui equal width grid">
    <div class="column">
      <%= render 'layouts/left_bar' %>
    </div>

    <div class="column">
      <%= yield %>
    </div>

    <div class="column">
      <div>
        <%= react_component'Email' %>
      </div>
    </div>

  </div>


  </body>

<div class="footer">
   Ruby / Rails / jQuery. Questionnaire 2017.
</div>

</html>

app/views/questions/export.js.erb
const str = "<div class='popup'><span class='popuptext' id='myPopup'>Saved to export.json</span></div>"

$('#saveButton').append(str);
showPopup();

app/views/questions/import.js.erb
let str = '';
let r = <%= @result %>;
if (r == 200) {
    str = "<div class='popup'><span class='popuptext' id='myPopup'>Imported</span></div>";
}
else {
    str = "<div class='popup'><span class='popuptext' id='myPopup'>Error !</span></div>";
}

$('#importButton').append(str);
showPopup();

app/views/questions/index.slim
.my-toggle
  #my_toggle.ui.toggle.checkbox
    input[type='checkbox' name='lang' checked=check_it data-remote='true' data-url='/toggle_language' data-method='get']
    label
      | jQuery

.ui.two.column.centered.grid.mystyle
  .two.column.row
    .column
      - if @questions.length > 0
        = react_component('QAButton', key: 0, btn_id: 'btn_1', question_id: @questions[0][:id], category: @questions[0][:category])
    .column
      - if @questions.length > 1
        = react_component('QAButton', key: 1, btn_id: 'btn_2', question_id: @questions[1][:id], category: @questions[1][:category])

  .two.column.row
    .column
      - if @questions.length > 2
        = react_component('QAButton', key: 2, btn_id: 'btn_3', question_id: @questions[2][:id], category: @questions[2][:category])
    .column
      - if @questions.length > 3
        = react_component('QAButton', key: 3, btn_id: 'btn_4', question_id: @questions[3][:id], category: @questions[3][:category])

#modal_form.ui.small.modal
  i.close.icon
  #myquestion.header

  #myanswer.content

  .actions
    #btn_ok.ui.approve.button
      | Ответ 
    #btn_cancel.ui.cancel.button
      | Закрыть

app/views/questions/no_questions.slim
p
  | There are no unanswered questions in this category !

app/views/questions/toggle_language.js.erb
window.location.reload();